apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend-svc
  labels:
    run: udagram-frondend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    run: udagram-frontend
