apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverse-proxy
spec:
  selector:
    matchLabels:
      run: udagram-reverse-proxy
  replicas: 2
  template:
    metadata:
      labels:
        run: udagram-reverse-proxy
    spec:
      containers:
        - name: udagram-reverse-proxy
          image: smami/udagram-reverse-proxy
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
