apiVersion: v1
kind: Service
metadata:
  name: udagram-reverse-proxy-svc
  labels:
    run: udagram-reverse-proxy
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    run: udagram-reverse-proxy
