apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-api
  name: udagram-api-svc
  namespace: default
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: udagram-api
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
